// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Xm3KAkF2aYZaDl9-VhIDJHSPsfAubMU',
    appId: '1:508342142554:web:017eaf76cf1967ff0d3a63',
    messagingSenderId: '508342142554',
    projectId: 'holo-35482',
    authDomain: 'holo-35482.firebaseapp.com',
    storageBucket: 'holo-35482.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkZLgT3Nh9LqKz8a8LZKoXOcRu3VRM1sc',
    appId: '1:508342142554:ios:9fac85b64aefdf050d3a63',
    messagingSenderId: '508342142554',
    projectId: 'holo-35482',
    storageBucket: 'holo-35482.firebasestorage.app',
    iosBundleId: 'com.example.holo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_Xm3KAkF2aYZaDl9-VhIDJHSPsfAubMU',
    appId: '1:508342142554:web:c505f879559890970d3a63',
    messagingSenderId: '508342142554',
    projectId: 'holo-35482',
    authDomain: 'holo-35482.firebaseapp.com',
    storageBucket: 'holo-35482.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkZLgT3Nh9LqKz8a8LZKoXOcRu3VRM1sc',
    appId: '1:508342142554:ios:83c718955bee41a00d3a63',
    messagingSenderId: '508342142554',
    projectId: 'holo-35482',
    storageBucket: 'holo-35482.firebasestorage.app',
    iosBundleId: 'com.example.holo',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbEfqZFpgdcGr9w3MZfG7eAmPnwENpDs8',
    appId: '1:508342142554:android:a1792ac9351e1e300d3a63',
    messagingSenderId: '508342142554',
    projectId: 'holo-35482',
    storageBucket: 'holo-35482.firebasestorage.app',
  );
}